### ISSUE TITLE
Recurring Event v2.2.0 cut 2 - Multiple issues

### ISSUE THREAD

**Issue by ghost** [Mantus667/EventCalendarBelle#10]
I have grouped the following as one github issue as they all concern recurring events.
1. Although there are many options for setting recurring event criteria, it is not possible to create a recurring event for a specific date, e.g. 25th December for Christmas Day, which could fall on any day of the week but will always fall on the same calendar day. This is particularly important for anniversaries etc.
2. Start and end time popups do not work when creating a new event. 
   ![untitled5](https://cloud.githubusercontent.com/assets/9944757/9411883/aaef2ae6-4820-11e5-90ae-c91e109bc4fa.png)

Refreshing the page populates the boxes with the current date time, and the popups are enabled.
1. Cannot save a recurring event without specifying both a day of week AND monthly interval, neither of which should be mandatory if a specific date is given as requested above.
2. When EDITING a recurring event which was initially saved as all day (a tick box), the flag button is shown off and cannot be set on (you can drag the control across but it just slides back to the off position). This applies to both IE11 and Chrome.
3. Cannot delete a recurring event once created. 
   ![untitled3](https://cloud.githubusercontent.com/assets/9944757/9411612/ed429632-481e-11e5-9ca3-2ff512ddc7df.png)

**Comment by Mantus667** [comment]
I will open a seperate issue for the feature request to be able to set a specific date as for recurring events. For me it should be implemented in 2.3 and not the current version.

**Comment by Mantus667** [comment]
Fixed the issue that recurring events can't be deleted.
Refactored the angular stuff for creating/editing recurring event to get rid of not loading issues for jQuery librarys.
Updated the switcher library to newest version.
