### ISSUE TITLE
Error when clicking event type root nodes in v2.2.0 cut 2

### ISSUE THREAD

**Issue by ghost** [Mantus667/EventCalendarBelle#11]
Having installed v.2.2.0 cut 2 (with the event types grouped in the tree) if you click on either the 'Normal Events' or 'Recurring Events' node in the tree under the calendar node, the attached error is generated. Chrome also generates the error.

![untitled2](https://cloud.githubusercontent.com/assets/9944757/9409441/8436a252-4812-11e5-91fa-dbb8a7b377fa.png)

**Comment by Mantus667** [comment]
This error comes from the new overview nodes in the tree. They had no view
assigned. Already added some overview views to them to remove the error and
also the blank page.

Closed
