### ISSUE TITLE
Normal Event v2.2.0 cut 2 - Date selection boxes are not initially populated

### ISSUE THREAD

**Issue by ghost** [Mantus667/EventCalendarBelle#12]
When creating a new event, the start and end date boxes are initially empty and the popup calendar does not work. This is the same for IE11 and Chrome
![untitled4](https://cloud.githubusercontent.com/assets/9944757/9411966/17e8849e-4821-11e5-899c-97d23d9f5887.png)

Simply refreshing the page in the browser populates the date boxes with the current date/time and the calendar popup then works.
![untitled6](https://cloud.githubusercontent.com/assets/9944757/9411996/4b34f47c-4821-11e5-8d45-a0c3f7216a0e.png)

**Comment by Mantus667** [comment]
Tryed to reproduce the issues and I know that they pop up sometimes.
Sadly I can't reproduce this behavior on a regular basis in IE11 or Chrome.

I moved the js files for the date stuff to package manifest so it gets loaded system wide.

Until I found a better way to reproduce this issue is closed
