### ISSUE TITLE
Server 500 with Umbraco 7.2.4

### ISSUE THREAD

**Issue by EppyGA** [Mantus667/EventCalendarBelle#3]
I've followed you're video tutorial to add to a site I'm playing with and whenever I click on the Calendar in the menu I get a 500 - Internal Server Error

You can look at umbraco.randallepstein.com

**Comment by Mantus667** [comment]
The current Version of the package doesn't support Umbraco 7.2.4
Will release a New Version this weekend build against 7.2.4

**Comment by Mantus667** [comment]
New version of package released. Build against 7.2.4
