### ISSUE TITLE
YSOD when viewing an event

### ISSUE THREAD

**Issue by ghost** [Mantus667/EventCalendarBelle#31]
I just installed the latest package (2.3.0) on a clean Umbraco 7.3 system. I created a new calendar and a single normal event. I then created a calendar and event details page in content. The event shows in the calendar but when clicked to go to the details page I get the attached error.
![2015-11-10_083335](https://cloud.githubusercontent.com/assets/9944757/11057782/ddea4684-8785-11e5-958f-781a6e292ed5.png)

**Comment by ghost** [comment]
Also, having upgraded an existing Umbraco 7.3 system from EC 2.2.0 to 2.3.0 I am now getting the following error when viewing an existing event. This event displayed without error prior to the upgrade.
![2015-11-10_084419](https://cloud.githubusercontent.com/assets/9944757/11057968/5df66cda-8787-11e5-92e6-9284c104c6e1.png)

**Comment by Mantus667** [comment]
Hi Rob,

thanks for reporting!
Think I found already what causes the issue. Will provide a fix this
evening if I can.

Regards
David
Am 10.11.2015 9:45 vorm. schrieb "Rob de Mercado" <notifications@github.com

**Comment by Mantus667** [comment]
Fixed mapping caused by null property
Fixed wrong model propertys in event detail page

**Comment by ghost** [comment]
Thanks David. Our dev system is now successfully upgraded to v2.3.1 with all looking good so far.
Regards,
Rob
