### ISSUE TITLE
Error saving changes to a Location

### ISSUE THREAD

**Issue by ghost** [Mantus667/EventCalendarBelle#4]
Having created and saved a new location, if I then select the location node (in this case Civic Centre) the edit page is displayed with a blank name (just the 'Enter a name...' placeholder). Any attempt to save the record results in an error. I am at present unable to save any changes to existing locations. All shown in the attached screenshot.
![1](https://cloud.githubusercontent.com/assets/9944757/8720374/4069411c-2baa-11e5-85e3-53ff5f915214.png)

**Comment by Mantus667** [comment]
Which Version if umbraco and EventCalendar are you using?
Had a similar issue a while ago but thought to have fixed it.
Will check again.

**Comment by ghost** [comment]
Hi David,
                I am using Umbraco version 7.2.5-RC assembly: 1.0.5591.28479 and EventCalendar package EventCalendar_2.1.4

Thanks and regards,

Rob de Mercado
Systems Developer
Ashford Borough Council
01233 330866

www.ashford.gov.ukhttp://www.ashford.gov.uk/
www.ashfordfor.comhttp://www.ashfordfor.com

[abc_twitter]https://twitter.com/ashfordcouncil

**Comment by ghost** [comment]
Similar problem with saving changes to an existing calendar. See screenshot.
![untitled](https://cloud.githubusercontent.com/assets/9944757/8748440/518800e4-2c92-11e5-8c63-08ef7cc74ca3.png)

**Comment by Mantus667** [comment]
Yes it seems that there are some database inconsistencies in this version
which are causing this bug.
Maybe you can verify that?

Do you have some way to reproduce that wrong behaviour?
Am 17.07.2015 15:44 schrieb "Rob de Mercado" notifications@github.com:

**Comment by ghost** [comment]
It is very easy to reproduce. Just create a new calendar (in the screenshot example mine was called 'Event Calendar'), refresh the Calendar node to show the new calendar, click the calendar node and the details are displayed as per the screenshot (note the empty name at the top). Clicking save produces the error. This behaviour (as with tall the issues I have discovered so far) has been replicated over three separate systems all of which have had the 2.1.4 package installed. I am more than happy to record a screen session .avi if it helps.

**Comment by Mantus667** [comment]
Hi Rob,

do you use IE11 while testing the package?
It seems that this behaviour only occurs in IE not in other browser.

**Comment by ghost** [comment]
Hi David,
You are quite correct this does appear to be an IE issue. I can confirm the issue with saving both events and locations does not occur in Chrome. Sadly our corporate browser is IE version 10 and 11 (FYI I am using version 11 for all my testing). Is this something which you think may be able to be fixed for IE?

Regards,
Rob.

**Comment by Mantus667** [comment]
Hi Rob,
sure I want to fix this issue. At least IE 10/11 should be supported.
I'm currently trying to look into the problem but haven't found anything
until now.

Regards
David

2015-07-20 12:25 GMT+02:00 Rob de Mercado notifications@github.com:

**Comment by ghost** [comment]
Thanks much appreciated. We are still very keen to use this plugin as it has great potential for us to extend it to suit our needs. This is exactly why we went the Umbraco route.

**Comment by Mantus667** [comment]
Hi Rob,
just a small update. Seems like I found the issues. There were  some
problems with a build in angular directive from umbraco and some other
angular related issues. I will test it in IE 10 and again in IE 11 to make
sure everything works now.

Regards
David
Am 22.07.2015 10:26 schrieb "Rob de Mercado" notifications@github.com:

**Comment by Mantus667** [comment]
Hi Rob,
I got a new test release ready for the new version of the package.
If you are interested to do some testing with the new version, send me a private email and I will provide you with a copy.

Regards
David
