### ISSUE TITLE
Events spanning multiple dates not showing correctly in calendar

### ISSUE THREAD

**Issue by ghost** [Mantus667/EventCalendarBelle#5]
I have created an event which spans 2 days, but it is only showing on the calendar for the first day. Attached screenshot shows calendar with event properties inlaid top left.
![2](https://cloud.githubusercontent.com/assets/9944757/8720576/6bd6560e-2bab-11e5-876c-398a8e1c4393.png)

**Comment by Mantus667** [comment]
Will check it out. Normally fullcalendar should handle that out if the box. Maybe there is something wrong with the dates so fullcalendar handle them wrong.

**Comment by ghost** [comment]
Hi David,
                Thanks again for your time. We are very seriously looking at using your package to replace the equivalent calendar in the CMS we are moving away from.

```
            I would like to try and extend your calendar so we can create our own pick list of event categories each with a different colour, and maybe add some other properties which we currently capture i.e. ticket prices.
```

Regards,

Rob de Mercado
Systems Developer
Ashford Borough Council
01233 330866

www.ashford.gov.ukhttp://www.ashford.gov.uk/
www.ashfordfor.comhttp://www.ashfordfor.com

[abc_twitter]https://twitter.com/ashfordcouncil

**Comment by Mantus667** [comment]
Hi Rob,

glad to hear that you have interest in my package.

If course you can fork the code and implement features that are missing. If
they are usable for public I'm surely interested to accept pull requests.

My feature plan as of now:
- improvements to recurring events and exception dates (currently in
  development)
- create locations through the create event page to not have the user leave
  the page
- changes to the event tree to group normal/recurring events and group
  normal events by year and month

I also thought about a way to let visitors register to an event (include
ticket prices, ecommerce connection), but thats not yet ready to even start
working on it.

Regards
David
Am 16.07.2015 12:35 schrieb "Rob de Mercado" notifications@github.com:

**Comment by Mantus667** [comment]
Hi Rob,
which Browser do you use?
Have tested the behavior with your time settings on IE11 and Chrome but the event spans on both days in both browser. So can't reproduce this error right now.

**Comment by ghost** [comment]
Hi David,
I'm not sure if the attached screen snippets will help. The problem here is on both IE11 and Chrome. The attached shows the calendar entry for a 3 day event but only spanning the first 2 days, with the event properties inlaid to the left. Note that the popup on the right of the calendar shows the event finishing at 12:00 AM and not 23:59 PM as set in the property.
![eventdate](https://cloud.githubusercontent.com/assets/9944757/8771524/985b067c-2eba-11e5-943c-0ecdd4d0dfe3.png)

**Comment by Mantus667** [comment]
Hi Rob,
thanks for the screens. They are indeed helpfull. Will try to reproduce it
with the settings you provided.

Regards
David

2015-07-20 9:38 GMT+02:00 Rob de Mercado notifications@github.com:

**Comment by Mantus667** [comment]
Hi Rob,

found the answer why this is happening. You can read it here:
http://stackoverflow.com/questions/27604359/fullcalendar-event-spanning-all-day-are-one-day-too-short

So it seems that it is a design decision that the last date is not added
when allday is used.

Regards
David

2015-07-21 19:39 GMT+02:00 David Brendel mantus667@gmail.com:

**Comment by ghost** [comment]
Hi David,
OK, I can sort of see what's going on here. Strange way of interpreting dates I have to admit but obviously out of your hands.

One other slight issue. If I go to edit an event previously saved as all day, the 'All Day' slider switch displays in the off position. If I save the record without changing anything it remains flagged as all day in the database. The only way to remove the all day flag in the database is to click the all day switch on and then off again and then save the record.
