### ISSUE TITLE
Tiny MCE configuration not pulling through

### ISSUE THREAD

**Issue by ghost** [Mantus667/EventCalendarBelle#6]
Hi David,
Apologies if I appear to be bombarding you with issues but we are keen to get this up and running for a user group demo as soon as possible.
This one concerns the rich text editor on the event details tab, which is not pulling through the customised toolbar or styles which we have set up. The following screen snippets show the Event details toolbar, and below it the more populated rich text editor which we have configured by editing the built-in Umbraco Richtext editor data type.
![tinymce](https://cloud.githubusercontent.com/assets/9944757/8748661/002aeb74-2c94-11e5-890a-d2ee5f8a6d6c.png)

**Comment by Mantus667** [comment]
Hi Rob,

don't worry. The more you report the better.

The rte currently uses a fixed config.
I added the request to my list and will change it while fixing the other
issues.
Am 17.07.2015 15:56 schrieb "Rob de Mercado" notifications@github.com:

**Comment by Mantus667** [comment]
Hi Rob,

I found some hacky way to pull through the default rte configuration to the custom section.
I will add it to the new release if all test for the current bugs are done.

Regards
David
