### ISSUE TITLE
Users are able to delete a location when in use by one or more events

### ISSUE THREAD

**Issue by ghost** [Mantus667/EventCalendarBelle#8]
It is possible to delete a location when it is in use by an event. This results in a YSOD when clicking the event in the calendar. Partial screenshot attached.

![deletedlocation](https://cloud.githubusercontent.com/assets/9944757/9386261/9250ca18-4752-11e5-97f3-c33080637a1f.png)

Users should ideally be prevented from deleting referenced dependency data.

**Comment by Mantus667** [comment]
Prevent users from deleting locations that are used
