### ISSUE TITLE
New Calendar - Name entry placeholder not showing (v2.2.0 cut 2)

### ISSUE THREAD

**Issue by ghost** [Mantus667/EventCalendarBelle#9]
This problem has appeared between the first cut of v2.2.0 and the second. When creating a new calendar, the 'Enter a name...' placeholder text does not display, although if you know where to click the textbox appears where it should. I have also noticed that in both cuts of 2.2.0 the textbox does not appear until you click in the correct place. The attached graphic shows (from top to bottom) 
1. v2.2.0 cut 1 displays the placeholder when creating a new calendar.
2. The textbox which only displays when the placeholder text is clicked.
3. v2.2.0 cut 2 with the absence of the placeholder text when creating a new calendar. This behaviour is observed in IE11 and Chrome.

![untitled](https://cloud.githubusercontent.com/assets/9944757/9408750/38e44cd2-480d-11e5-9d71-2d061ef90885.png)

**Comment by Mantus667** [comment]
Added a static placeholder until the angular stuff works also in ie11
